### ISSUE TITLE
MH Block Proposals

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#136]
Adding some sort of block proposals in MH would be very beneficial for many models, but specifically for models that implement Bayesian learning.

As it is right now, proposing the prior element to some parameter will result in a new set of elements being created based on the new prior value. The problem is that from a learning point of view, the new elements have not been "burned-in" (so to speak) by the observations. This results in rejection of the new parameter, even though, after several MH iterations, the new parameter may be a better fit for the data than the old parameter.

We could solve this by adding some sort of block proposal, where we could propose to change the prior value and all the parameter values as once, and compute a proposal distribution based on all the parameters, not just the prior.

**Comment by apfeffer** [comment]
It's worth putting thought into how to expand the DSL for proposal schemes.

**Comment by apfeffer** [comment]
I think it's worth scheduling review and improvement of our MH implementation for the summer/fall, now that we've spent so much time on factored inference.
