### ISSUE TITLE
Create abstraction for generating samples from a universe

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#246]

**Comment by apfeffer** [comment]
An algorithm could provide a method to generate a sample from the posterior distribution over a set of variables.

MH.generate(...)
Importance.generate(...)
VE.generate(...)

Generate a stream of samples - or provide number of samples to generate

**Comment by apfeffer** [comment]
@bruttenberg Brian, this is important and something we've needed for a long time. I'd like to put it on the agenda as soon as you've finished SFI with MAP.

**Comment by bruttenberg** [comment]
This is tricky. I don't think we can let a user arbitrarily sample from the posterior of any variable, as we'd need to track the posterior for every variable in the model, which is not feasible.

Do we want to assume its the marginal posterior if we let the user specify variables? Or the joint? This could make a big difference.

**Comment by apfeffer** [comment]
I think the idea is to generate samples from the joint posterior. However, we only need to store the values of the target variables.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment]
Ok. The main issue with this task is that joint posterior sampling is highly algorithm dependent and will be completely different depending on the algorithm used.

Also, for BP we'd have to change the model to form a joint factor, which could cause problems.

**Comment by apfeffer** [comment]
I assume we’d only use importance sampling or MH.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment]
Checked in and merged for MH and IS

**Comment by guyyos** [comment]
Hi, not sure if this is the correct thread. I need to generate samples from my model. What is the best way to do it? Is the code discussed above is in the official version of Figaro (master trunk)? how to use it?

**Comment by apfeffer** [comment]
Hi,

This is a good question, and it has been asked on the book forum. Please see https://forums.manning.com/posts/list/38706.page for a discussion.

Thanks,

Avi
