### ISSUE TITLE
Factors for tuple elements are prohibitively big

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#267]
The size of factors for tuple elements will always be the square of the number of possible tuples. For example, creating a pair from two elements that each have a range of 30 possible values would result in 900 possible tuples, which would create a factor with a size of 810000. This is an issue for other compound elements as well, but is most pronounced for Apply elements where every input produces a unique output. Without an improvement for this, it becomes impractical to perform factored inference on undirected models.

**Comment by bruttenberg** [comment]
Fixed with sparse factors
