### ISSUE TITLE
Dependency creation in Importance sampling is slow and not always needed

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#270]
The dependency computation in Importance sampling to propagate evidence through Dists and Chains is horribly slow. That aside, the dependencies are still being pushed when there is no evidence. If there is no evidence, or there is no evidence on any chain or dist, this code should be skipped.

**Comment by apfeffer** [comment]
@bruttenberg Could you look into this and see if this is still a problem, and, if so, do we want to solve it?

**Comment by bruttenberg** [comment]
I fixed this with the rewrite of LW last summer. The dependencies are now dynamically created during samples, similar to your suggestion from above. If, during sampling, it determines that it processed an element inside a chain before the chain, it re-samples the element with the proper likelihood weighting. This gets around calling values during IS as well. I'm closing this.
