### ISSUE TITLE
Figaro "new"

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#319]
BLOG allows you to sample from all instances of a given class, or quantify over them. Figaro currently doesn't have a way to know what instances of a class exist in a given possible world. It would be nice to provide a type of container that has a new method to instantiate new instances that keeps track of the instances. This container should also provide a clear method. A more advanced implementation would also provide the ability to free individual instances.

MakeList provides a basis for implementing this. We could use an infinite stream of elements, in which only some were active at a given time. This would allow us to avoid reinstantiating large numbers of elements.

**Comment by bruttenberg** [comment]
Avi, is this subsumed by containers?
