### ISSUE TITLE
HierarchyTest MH test fails

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#326]
This test fails intermittently, about 1 in every 10 times or so. It produces an answer 0.0 instead of 2/3. This is the case for the 3.0.0 development branch up on GitHub without my changes.

Brian, can you investigate?

**Comment by mreposa** [comment]
I ran this test 50 times using the most current Figaro 4.0. It failed once and was not off by much:

[info] HierarchyTest:
[info] A simple HierarchyTest
[info] - should produce the correct probability under variable elimination (1 second, 554 milliseconds)
[info] - should produce the correct probability under importance sampling (1 second, 267 milliseconds)
[info] - should produce the correct probability under Metropolis-Hastings *** FAILED *** (1 second, 929 milliseconds)
[info]   0.6879336478191923 was not 0.666 plus or minus 0.02 (HierarchyTest.scala:111)
