### ISSUE TITLE
ContinuousTest compound element MH tests fail too  often

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#327]
I've noticed that several of these tests fail once every few times. These include CompoundNormal, CompoundGamma, and CompoundBeta.

One possibility is that this is related to Synapski's recent changes.

Mike, is there any way to check whether these failures also happen in a version before Synapski's continuous element changes were merged?

**Comment by apfeffer** [comment]
Change tolerances so they don't fail as often

**Comment by bruttenberg** [comment]
This was fixed with the new ND testing
