### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#360]
We have the tutorial in Latex, the release notes and quick start guide in Word, and also a README in GitHub. Some of the same material appears in different places and ideally should have one source.

One solution is to make the release notes and quick start guide be in Latex and draw on the tutorial source, and make the GitHub README be brief and point to the other information.

**Comment by mreposa** [comment]
We also have two Web sites that we maintain content on as well as the documentation, so putting this all in LaTex isn't the best solution. We need to discuss this in more detail.

**Comment by apfeffer** [comment]
Waiting for Karen's input.
