### ISSUE TITLE
Problem with factorCache (possibly other caches with Element keys)

### ISSUE THREAD

**Issue by gtakata** [p2t2/figaro#370]
On investigating why VE is slow on the TIDE model, it turns out that the factorCache does not discover previously cached factors. The reason seems to be that Map lookups are based on equals and hashCode semantics, which, by default, are based on reference equality.

Elements created independently, even though they should be equal, are not. For example, when
val x = Constant(10) and val y = Constant(10), x and y are not equal.

In the Factor class, a Factor cached using x will not be found when looked up using y.

One possible solution would be to override equals and hashCode so that equality holds appropriately, eg when Constants have the same value. However, this may be difficult for more complex Elements.

One problem is that Element already overrides hashCode and creates a new hashCode for every new Element (I'm not sure why). In order for hashed containers, eg Maps and Sets, to work consistently, objects that are "equal" should have the same hashCode.

**Comment by bruttenberg** [comment]
This is correct behavior; x and y are different variables, and hence they should have different factors. The fact that they have the same distribution is true and we could use that to reduce the factor creation time. These are different variables and should not be equal.

The reason that element overrides equality and hashcode is that to enable repeatable computation using a set random seed, we have to ensure that everything about an element is recreated for every run, including its hash code (which is not the same between runs).

Brian



+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
