### ISSUE TITLE
Collections chain function name

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#372]
I realize its too late for Figaro 3.0, but the collections .chain function should really be renamed .flatMap to maintain consistency with 1) elements .flatMap and 2) scala functional terminology

**Comment by apfeffer** [comment]
Add "val flatMap = chain" to Process and Container.

**Comment by AliOC** [comment]
The above line of code was giving me errors: I ended up adding, 

def flatMap[Value2](f: Value => Element[Value2]): Process[Index, Value2] = { chain(f) }

and the similar line for Containers. Ready to commit this if this looks right.

**Comment by gtakata** [comment]
Should be: def flatMap[Value2]: Process[Index, Value2] = chain(f) ….. yes? (brackets on Value2)

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by AliOC** [comment]
Yes, copy and paste doesn't work well on GitHub and removed them. The tests for this passed.

**Comment by gtakata** [comment]
Cool. Looks fine to me.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>
