### ISSUE TITLE
NonDeterministic random bug in VE?!

### ISSUE THREAD

**Issue by gtakata** [p2t2/figaro#393]
VETest occasionally produces this error:

VETest:
.....
Running VariableElimination
- should with no conditions or constraints produce the correct result
- should with a condition on a dependent element produce the result with the correct probability
- should with a constraint on a dependent element produce the result with the correct probability
- should with an element that uses another element multiple times, always produce the same value for the different uses
- should with a constraint on an element that is used multiple times, only factor in the constraint once *** FAILED ***
  0.48 was not 0.73 plus or minus 1.0E-7 (VETest.scala:490)
.......

The problem is:
1) VE is deterministic so the discrepancy should be computational, eg rounding error, but a difference of .25 is to large to be this sort of error.
2) While the error occurs randomly, it is always 0.48. Whatever is happening always produces the same error.

**Comment by bruttenberg** [comment]
I've narrowed this bug down to a problem with sparse factor products. In this case, where one variable shows up multiple times in a factor. The following code with deterministically reproduce the bug:

Universe.createNew()   	
	val f = Flip(0.5)
    val e = f === f

    val v1 = new Variable(ValueSet.withoutStar(Set(true, false)))
	val v2 = new Variable(ValueSet.withoutStar(Set(true, false)))
    
	val f1 = new BasicFactor[Double](List(), List(v2))
	f1.set(List(0), 0.5)
	f1.set(List(1), 0.5)
	
	val f2 = new SparseFactor[Double](List(v2, v2), List(v1))
	for {
	  i1 <- 0 to 1
	  i2 <- 0 to 1
	  i3 <- 0 to 1
	} {
	  val index = List(i1, i2, i3)
	  if ((v2.range(index(0)).value == v2.range(index(1)).value) && v1.range(index(2)).value) f2.set(index, 1.0)
	  else if ((v2.range(index(0)).value != v2.range(index(1)).value) && !v1.range(index(2)).value) f2.set(index, 1.0)
	  else f2.set(index, 0.0)
	}
    
	val result = f2.product(f1, SumProductSemiring)	
    println(result.sumOver(v2, SumProductSemiring).toReadableString)
