### ISSUE TITLE
Factors for parameterized elements

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#398]
Currently, making factors for parameterized elements uses the MAP value of the parameters. This avoids us having to create any factors at all for the parameter. This is exactly what we want for EM.

However, for regular inference, we want to reason over the distribution over the parameter. This is true if we’re doing Bayesian learning, but also if we’re not learning at all. When we first made the decision to use the MAP value, we didn’t have factors for continuous elements. 

It seems we have two different use cases, both of which are valid, and which are mutually exclusive. Do we want to offer the user a choice? Do we want to implement one of them as the default? A simple solution is to require the user to explicitly make a Flip parameterized when creating it, rather than assuming it based on the argument being a Beta.

**Comment by apfeffer** [comment]
Michael:

I could easily add something like this along with issue 332 (https://github.com/p2t2/figaro/issues/332)

You could have a method in the Flip object called ‘parameterized’ or something similar. Then, you could do:

val f = Flip.parameterized(Beta)

or something similar.

**Comment by apfeffer** [comment]
Avi:

That sounds like a good solution, but I don’t see what it has to do with issue 332.

**Comment by apfeffer** [comment]
Brian:

So, I’ve run into trouble with this before trying to make non-parameterized versions of elements – I didn’t realize it created a parameter when what I wanted was just a simple element. 

The choice of parameter or not is really algorithm dependent. Is there some way we could delay the creation of the type of element until the algorithm is invoked?

**Comment by apfeffer** [comment]
Glenn:

It depends on the signatures and the learning methods. Right now you can convert factors to other types using convert and map, eg you can convert a Factor[Double] to Factor[Double, Double] then use factor.mapTo convert the factor to use a SumProductUtilitySemiring.

I think we already do this with the SufficientStatisticsFactor. Then the methods to handle learning can be applied from an external object.

**Comment by apfeffer** [comment]
It looks like being a parameterized element only matters in two ways - Michael correct me if I'm wrong.(1) It defines a density method as if the element is atomic, using the parameter's MAP value. (2) Creating a factor makes a factor like for an atomic, using the MAP value, instead of a factor for a compound.

It seems like the only real issue is we want to create factors in the appropriate way. We could certainly leave that up to the algorithm - this is in keeping with the new philosophy of giving as much control as possible to the algorithm. We could add an optional flag to the method that creates factors for an element to treat the element as parameterized if possible. This would involve minimal modification to existing code.

If this is the right solution, I'll go ahead and do it.

**Comment by mhoward2718** [comment]
I think you are right, and since we want the factor creation strategy to be part of the algorithms, it seems like the right choice.

**Comment by bruttenberg** [comment]
Yes Avi, I think this is the right solution. Please go ahead and make the change.

**Comment by apfeffer** [comment]
This issue has been fixed in SFI and checked in with the recent commit.
