### ISSUE TITLE
Add conversions from collections to variable argument lists

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#411]
Many elements take a variable argument list as input, but most model design uses scala collections to contain probabilities and such. The onus right now is on the user to convert these collections to variable argument lists using _*, which is clunky. We should add an implicit conversion from a scala collections to variable arguments so the user doesn't have to do it themselves.

**Comment by gtakata** [comment]
Do you have a specific example in mind? I know Selects, for instance, have constructors (apply) that use variable lists, but the classes themselves use lists, eg of clauses, so you can create the AtomicSelect directly using a List without going through the object, which uses _*

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
This should be added into the objects. Selects is a good example.

Right now we have:

def apply[T](clauses: (Double, T)*)(implicit name: Name[T], collection: ElementCollection) =
    new AtomicSelect(name, clauses.toList, collection)

But we can add something like this:

def apply[T](clauses: Iterable[(Double, T)])(implicit name: Name[T], collection: ElementCollection) =
    apply(clauses:_*)


+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by bruttenberg** [comment]
This change is tricky. You can't actually use implicits to convert from a sequence to a variable argument list. Our only choices here are to change the interface to every algorithm/element, or add new functions in the algorithm/element objects that do the conversion.

**Comment by bruttenberg** [comment]
We won't make this change. It will provide some syntactic sugar benefit to the user but will require too many new functions or break existing functionality.
