### ISSUE TITLE
FactoredFrontier bug

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#416]
In creating tests for code coverage, I came across this issue. 

Using the 'anytime' version of FactoredFrontier seems to crash immediately. The reason is because in AnytimeInnerBPHandler, in the CreateBP method, there is check to kill the instance of the BP algorithm if it is not null. However, when first running the FF algorithm, the inner BP is not null, but also inactive. The kill method throws an exception when this is the case.

It's easy to fix this by just checking if the BP algorithm is active in the CreateBP method.

**Comment by bruttenberg** [comment]
Great find. Proof that we needed more coverage!

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
