### ISSUE TITLE
How to build large Bayes Nets?

### ISSUE THREAD

**Issue by sandro-felicioni** [p2t2/figaro#444]
Hi there,

I have to build a large and dense Bayes Net with many thousands of nodes and I was looking for an easy way to specify a CPD with more than five parents. Looking at the code (e.g. the CPD class) and reading the User Guide it seems like it is only possible to specify five parents at most. Do you have any idea how to implement such thing with say ten parents?

Many thanks

**Comment by apfeffer** [comment]
Hi,

The way to do it is to use tuples. If you have ten parents, you could create two tuples of five parents each. Then you can create a CPD with the two tuples as parents.

For example:

val tuple1 = ^^(parent1, parent2, parent3, parent4, parent5)
val tuple2 = ^^(parent6, parent7, parent8, parent9, parent10)

val child = CPD(tuple1, tuple2,
  ((0,0,0,0,0),(0,0,0,0,0)) => etc.

Please excuse me - I may not have the syntax 100% correct as I'm working remotely.

Please let us know how it goes with your very large Bayes net.

Thanks,

Avi



On Apr 26, 2015, at 10:14 AM, sandro-felicioni <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there,

I have to build a large and dense Bayes Net with many thousands of nodes and I was looking for an easy way to specify a CPD with more than five parents. Looking at the code (e.g. the CPD class) and reading the User Guide it seems like it is only possible to specify five parents at most. Do you have any idea how to implement such thing with say ten parents?

Many thanks

-

**Comment by bruttenberg** [comment]
I would agree with Avi that tuples are the best route, but you could also uses a series of Chains if you find that easier.

Please feel free to ask more questions as they come up, including any regarding inference on your large network.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
