### ISSUE TITLE
Anytime algorithms can crash when run in sequence on the same universe

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#455]
If we repeatedly create and run anytime algorithms on the same universe, a crash can occur. This is because when the anytime algorithm is killed, it calls 'cleanUp.'. In an algorithm like anytime annealing, this calls Universe.clearTemporaries. There is no guarantee that this will be finished by the time the next algorithm begins running on the universe, and can modify some of the maps inside Universe while other algorithms are using them. This leads to key-not-found exceptions.

I have a solution that eliminates the problem, but I'm not sure if it's what we really want to do. The idea is to add `case "cleanup" => cleanUp()` to the algorithm runner, and to use `runner ! "cleanup"` in `shutdown` instead of of a normal function call to cleanUp().

**Comment by gtakata** [comment]
From an actor point of view, a better approach would be to start a new Actor for each create rather than reuse the old one. This allows the “old” actor to finish its cleanup and die a natural death. Of course you’d need to recreate the universe for the new Actor.

An alternative is to use a Future object and make the next process(es) wait until the Future returns. This, however, will need to block while the cleanup is being done.

If restarting after a pause, do not call cleanup, but define a separate process to deal with transitions, etc, between steps.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by gtakata** [comment]
The suggested solution really doesn't solve the problem, all it does is push it up the chain one step. Note that the cleanUp() will still be run in either case and that any other process trying to share the same Universe (Actor or not) will be affected. This is a concurrency problem and, unless specifically written to do so, Akka Actors will not help (out of the box, they don't block or guarantee atomicity).


We can use special forms to do this, eg Futures/Promises or explicit blocking, but it's not there now.

________________________________

**Comment by mhoward2718** [comment]
Okay - Here is my new, simplier diagnosis. Right now, the `shutdown` method in anytime looks like this:

```
  def shutdown {
    cleanUp()
    if (running)
    {
    	runner ! "kill"
    	system.stop(runner)
    	system.shutdown
    }
  }
```
Note that cleanup is called before the runner is killed or the system is stopped. The algorithm is still running while `cleanup()` is happening.

 So, my new solution is to do `cleanup` after the algorithm is shutdown. From our discussion on Wednesday, I realized that the the conflict that causes the exception is not what I identified in the original issue. The next algorithm is actually not being run on the same universe that cleanup is called on. So, this could potentially happen whenever an Anytime algorithm runs on a large model and is shutdown. 

Is there any reason to cleanup before killing the algorithm?

**Comment by gtakata** [comment]
In the test instance you don’t need to clear temporaries, so you can change cleanup to just return without doing anything. This is just there in case you need to take care of side effects, like printing something to a log or shutting down a db.

Check out where kill goes. It may be doing other cleanup stuff.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by gtakata** [comment]
This doesn’t make sense. If no other algorithm is using the Universe during the cleanup, then who is getting the not found error?

System.stop and System.shutdown don’t have much to do with the algorithms. They will shut everything down regardless. So unless the kill command is directed to do something else, there must be a leak and some other algorithm is trying to use the same Universe.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
I'm confused on this current problem. Can you post some code to replicate this?

What I don't understand is how the call to cleanUp is handled. Is this a blocking or non-blocking call? If this is blocking, then there shouldn't be a problem UNLESS someone is killing the algorithm before stopping the algorithm. If this is a non-block call, then we need to find a way to make it blocking.

**Comment by gtakata** [comment]
The Akka Actor call is non-blocking (it’s just a message). If you really want it to block, it needs to be done in the algorithm or trait, since the method can be called in OneTime as well as Anytime algorithms.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Yeah, but the way it’s set up in the code the cleanup is not invoked via a message, so not sure its non-blocking.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
