### ISSUE TITLE
Unified graph traversal method

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#457]
There are many places in the code base where an algorithm needs to traverse a set of elements in generative order and do something at each element (eg, MH, Importance sampling, Forward sampling). This code is different in each place, but it really should be unified to prevent bugs and simplify the code.

**Comment by gtakata** [comment]
What is generative order?

Maybe there should be a function to generate an efficient ordering, eg for VE, that can be consistently applied for other purposes. There are several places where a dependency graph is either explicitly (BP, SFI) or implicitly (Universe used/usedby) that could be used for this.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Generative order is defined by the generative process of a model, ie, generating values for a parent before the child. You can’t generate an efficient ordering, it’s fixed by the definition of the model.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by bruttenberg** [comment]
This is nominally supported by the new Likelihood Weighting class, though it does not work for MH.
