### ISSUE TITLE
Online EM doesn't always retrieve sufficient statistics correctly

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#461]
Depending on how the model and transition is defined, Online EM won't always correctly retrieve sufficient statistics when using algorithms like BP or MH.

**Comment by bruttenberg** [comment]
Can you either add more detail on this bug or post some code to reproduce it? There’s no way for anyone else to look into this given the description.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by bruttenberg** [comment]
Michael, can you please either add the code to reproduce this or provide a description of the bug?

**Comment by mhoward2718** [comment]
Variable Elimination uses a special factor type to compute sufficient statistics. The other algorithms  compute statistics from algorithm.distribution(). In batch, these come out the same. In online situations where every parameterized variable in the model has evidence applied to it, they also come out the same. But, when the parameterized variables do not always have evidence in every time step, the statistics computed by BP, Importance and MH don't match what's produced by VE. So, they are at least inconsistent with each other, and I think what's computed by VE is correct.

By the way, #462 doesn't completely fix the problem and so this bug should stay open.
