### ISSUE TITLE
Concurrent calls to Universe.createNew() might not returned created universe

### ISSUE THREAD

**Issue by lfkellogg** [p2t2/figaro#469]
When calling `Universe.createNew()` concurrently from multiple threads, the universe that is created on a particular call is not always the one that is returned. If the method is simultaneously called from another thread, the `universe` var can be overwritten before the value is returned. I noticed this because it was causing some problems with the new parallel particle filtering we're working on.

I don't even think this necessarily needs to be changed. I just think the behavior should be clear from the scaladoc, now that we are going to be doing more multi-threading. For example, you may really want it to return the current default universe, as it does now, although in that case it might be better to simply not return anything and make users refer to the `universe` var to access it. At least that way it would be more clear that it is not thread-safe, plus it would suggest that using `new Universe()` is a more appropriate way to simply create a new universe when the default universe is not relevant, such as when defining a transition function for PF.

If you do want to change it, you could just use a temp variable, like this:

    def createNew(): Universe = {
      val temp = new Universe
      universe = temp
      temp
    }

**Comment by bruttenberg** [comment]
Lee, concurrency is a big issue in general in Figaro and we really don’t have any guarantees on thread-safe operations. I agree that may more documentation is needed to make sure that people are aware that there are side effects of the calls and that it’s not thread safe. As you note, you can always just call new Universe. In hindsight, maybe the Universe.createNew should be something like Universe.newDefault to imply that it’s really setting the default.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
This should be part of our review of Universe, Element, etc., as part of our code cleanup. The problem is not the creation of Universe itself, but the operations inside the creation. These should all complete before the create method returns, ie the create method itself should be atomic.

BTW The solution proposed does not prevent a race condition, viz, what if another thread updates universe while you are creating a new one? Then when you assign universe = temp, you will be overwriting their universe with your new one.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Good point, let’s bin this into the code cleanup of Universe.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by lfkellogg** [comment]
@bruttenberg "In hindsight, maybe the Universe.createNew should be something like Universe.newDefault to imply that it’s really setting the default."

I think that's a good idea. Right now, at least to a Figaro newbie like myself, the createNew() name implies that "this is how you create a Universe," and the fact that it returns one says "here's your new universe."

@gtakata "what if another thread updates universe while you are creating a new one?"

Correct, this doesn't actually make the operation thread-safe with regards to modifying the default universe. This just makes it so if you use createNew() to create a universe, you will at least get that one back (if that's the desired behavior). I honestly think renaming it like Brian suggests or making it return Unit would be better than changing how it works.

**Comment by curtwu** [comment]
It seems like the intent of this function is to (1) create a new Universe; (2) allow this new Universe to be set as the default for convenience, so future calls do not need to specify a Universe. The latter is causing the concurrency problem. Can we remove the default Universe altogether?

**Comment by bruttenberg** [comment]
No, we can’t. The default is implicit so that users don’t have to mess with universes if they don’t have to. Please keep in mind that Figaro in general is NOT thread safe, and fixing the concurrency problem here will not solve all the problems – there will be more!

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
I'm comfortable with changing the name of Universe.createNew to something more appropriate, as long as we maintain backward compatibility.

I'm more concerned with the safety issue. It should be guaranteed that the universe that is created is the one that is returned. Lee's fix with the temporary variable will achieve this. I'm not as concerned that it should be the default universe on method end. The semantics of Universe.createNew has always been that it sets the default universe until someone changes it. I'm comfortable if "someone changes it" is another thread running concurrently. If you're using a multithreaded application where each thread is changing the default universe, you shouldn't be relying on the identify of the derault universe staying stable.
