### ISSUE TITLE
universe.assertEvidence is not the same as observation

### ISSUE THREAD

**Issue by mhoward2718** [p2t2/figaro#473]
This program runs as expected:
```scala
  def mhExperiment() = {
    val u = Universe.createNew()
    val e = Flip(0.50)("flip", u)
    e.observe(true)
    val alg = MetropolisHastings(1,ProposalScheme.default, e)
    alg.start
    alg.stop
    alg.kill
  }
  
  def main(args: Array[String]) = {
    for (i <- 0 to 100000) {
      mhExperiment
    }
  }
```

This code will crash:

```scala
  def mhExperiment() = {
    val u = Universe.createNew()
    val e = Flip(0.50)("flip", u)
    u.assertEvidence(List(NamedEvidence("flip", Observation(true))))
    val alg = MetropolisHastings(1,ProposalScheme.default, e)
    alg.start
    alg.stop
    alg.kill
  }
  
  def main(args: Array[String]) = {
    for (i <- 1 to 10) {
      mhExperiment
      println("Ran experiment " + i + " times.")
    }
  }
```

The reason is because in UnweightedSampler, certain internal maps (initUpdates) will only be populated if the first sample is accepted:

```scala
  protected def doSample(): Unit = {
    val s = sample()
    if (sampleCount == 0 && s._1) {
      initUpdates
    }    
    if (s._1) {
      sampleCount += 1
      s._2 foreach (t => updateTimesSeenForTarget(t._1.asInstanceOf[Element[t._1.Value]], t._2.asInstanceOf[t._1.Value]))
    }
  }
```
The cause of the crash mentioned above is a key-not-found exception from initUpdates in MetropolisHastings, because the initial sample was not accepted. There must be something different about asserting an observation through a universe versus directly observing the element that causes the sample to be rejected.

Strangely, though, it's not deterministic when the program will crash. Sometimes it works, sometimes it doesn't. But, it will almost surely crash within 10 repetitions of the experiment.

**Comment by bruttenberg** [comment]
Two things here:

1, I actually have a fix for the crash on my machine already, so this no longer crashes. 
2, I took a look at the code and an Observation actually sets a condition instead of an observation. This should be changed.

**Comment by bruttenberg** [comment]
Actually, this may have been done intentionally. If you change it to an observation, then you can't propagate contingent evidence

**Comment by bruttenberg** [comment]
Closing this issue. Using references, an observation will not be the same as a direct observation on an element. Mathematically they are the same, but because the reference will use a condition instead of observation, we won't be able to use things like Likelihood weighting on it.

**Comment by gtakata** [comment]
This behavior should be documented somewhere even if it not an issue.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by bruttenberg** [comment]
Good point. I will reopen to make sure it’s done.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by bruttenberg** [comment]
Comment added in Scaladoc for observation.
