### ISSUE TITLE
Sampling only relevant elements in algorithms

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#479]
Forward sampling, PF, and Importance sampling sample all of the elements in the universe on each iteration. This means that temporary, active, but possibly non-relevant elements are sampling each iteration. For instance, the entire path of elements used from a particular value of a chain's parent may not be needed if the parent of the chain is sampled to a different value. 

Instead, we should use the same concept as in lazy variable elimination. Starting from the relevant elements in the universe (where relevant can be defined as the targets in Importance sampling, or named elements in PF), recurse backwards through the model and only sample the elements that will be relevant.

**Comment by bruttenberg** [comment]
This is tricky because there is a test in Figaro that is checking for this exact condition. It looks like this:

"resample elements inside class defined in a chain" in {
      Universe.createNew()
      class temp {
        val t1 = Flip(0.9)
      }
      val a = CachingChain(Constant(0), (i: Int) => Constant(new temp))
      val b = Apply(a, (t: temp) => t.t1.value)
      val alg = Importance(10000, b)
      alg.start
      alg.probability(b, true) should be(0.9 +- .01)
      alg.kill
    }

If I recall, this was added because sampling only the permanent elements in IS will miss cases where you have elements inside  other elements. Normally, this should be ok since you'd have a chain somewhere to lift the hidden element up to the top level model somewhere. The example above gets around that dependency by accessing the value of a hidden element directly. So the question is, is this a valid Figaro operation, and should it be supported?

**Comment by gtakata** [comment]
Is SFI applicable to this the kind of situation? The Problem is to sample from b, but b has a nested Problem to sample from t1.

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>
