### ISSUE TITLE
Syntactic sugar to replace Dist

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#481]
The Dist element is really just implementing a combined Select and Chain, and we have special handling in sampling algorithms to handle this particular distribution. But we can really just replace Dist with a synactic sugar call that makes a Select and a Chain with the same functionality. This would allow us to remove the special code that handles Dist.

**Comment by apfeffer** [comment]
Dist is not simply syntactic sugar for Select and Chain. I made the decision early on to model it differently because algorithms might want to treat it specially. I don’t think we should change that.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by bruttenberg** [comment]
But there’s nothing special in the way Importance sampling or Forward sampling handles it. If you replace it with a select and chain, those algorithms will work fine.


+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
SFI might want to handle it differently. Currently it does.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by bruttenberg** [comment]
If you really want to keep it, we can. But any algorithm has to handle the functionally equivalent formulation as a select and a chain (as I could code one up in my model), and unless the algorithms are doing some optimization/enhancement/improvement knowing that it’s a Dist, there’s really no benefit.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
I think there might be a benefit – I’m not convinced there’s not – so I would prefer to keep it.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513
