### ISSUE TITLE
Loading a CPD from a file?

### ISSUE THREAD

**Issue by toncho11** [p2t2/figaro#482]
Hi,

1) Is it possible to load a CPD from the file system?

A CPD in Figaro requires all combinations to be provided. In my case I have 4 variables with respectively 3,4,10 and 13 values each. So I need to provide 1560 lines in my CPD:

Example: 
(1,1,1,1) -> Select (0.429541 -> 1, 0.937202 -> 2, 0.365797 -> 3, 0.735122 -> 4, 0.902541 -> 5, 0.569422 -> 6, 0.160745 -> 7, 0.363769 -> 8, 0.478310 -> 9, 0.051716 -> 10, 0.364739 -> 11, 0.339749 -> 12, 0.747897 -> 13)

The output is also from 1 to 13. 340kb of the above probabilities turns up to be too much for a Java based Scala IDEs. And yes it is no brainer that the above data should not be kept in the source code.

I use VariableElimination for my algorithm. The RichCPD seems incompatible with VariableElimination? I can not compile RichCPD as an exact replacement of CPD.

2) Would the VariableElimination work with such a big CPD?

**Comment by bruttenberg** [comment]
Hi,

You can’t load a CPD directly from a file system (as in a serialized class), but there should be no reason you can’t read in the cases and probabilities using Scala’s IO and automatically build a CPD. We do it all the time. For example

val lines = scala.io.Source.fromFile("file.txt").getLines()
val cases = lines.map{line =>
  // parse lines
// return a (Tuple4, Element[Int])
}
val cpd = CPD(cases:_*)

As for the RichCPD, Figaro’s Variable Eliminiation algorithm can handle models with RichCPDs. VE will have a really hard time on such a large CPD. You’ll probably want to use some sampling algorithm instead.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
