### ISSUE TITLE
Possible Ch 8 code typo

### ISSUE THREAD

**Issue by d10genes** [p2t2/figaro#485]
In ch. 8 of the tutorial, I'm having trouble parsing a [line](https://github.com/p2t2/figaro/blob/master/FigaroLaTeX/Tutorial/Sections/8LearningParams.tex#L146) that reads `Select(parameters.get("fairness" + datum._1), outcomes: _*)`.

Here, `datum` has type `(Int, Int, Int)`, so it appears to be adding an int to a string. I'm newish to scala and may be mistaken, but it seems there could be a missing paren somewhere.

**Comment by d10genes** [comment]
Looking at it again, it looks like the previous [lines](https://github.com/p2t2/figaro/blob/master/FigaroLaTeX/Tutorial/Sections/8LearningParams.tex#L122) should be defining names with integer suffixes (i.e., "fairness1", "fairness2", etc., though they all say "fairness1"). Then I think this line is attempting to concatenate the string with a numeric suffix (but I would have thought in Scala you would need to cast the int to a string first).

**Comment by apfeffer** [comment]
Hi Chris,

In Scala, you can concatenate any object onto a string using the string + method. It automatically uses the toString method of the object.

Does that answer your question?

Avi

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by d10genes** [comment]
Yes, that makes sense. Thank you!
