### ISSUE TITLE
Should algorithms report their progress?

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#491]
When running long-running algorithms, it can be useful to view their progress. For example, number of samples taken, number of iterations of BP, number of iterations of EM. Can we make algorithms report their progress, either automatically or by flag?

**Comment by bruttenberg** [comment]
I think for the most part, the algorithms have this information, but it’s usually not available to query. By report, do you mean some standard API for this?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gtakata** [comment]
I think this would be most useful for interactive use, even if it means the user has to kill the process manually to stop a long-running job. The progress could be reported to the console or to a log.

This leads to another question. Should be provide logging for algorithms? Especially long-running ones and those which may report unusual conditions?

*********************
Glenn Takata
Charles River Analytics Inc.
617.491.3474 x625
www.cra.com<http://www.cra.com>

**Comment by apfeffer** [comment]
Simply printing to output would suffice. Just something so someone who’s using an algorithm can have an estimate of how long it would take.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by apfeffer** [comment]
Case in point – I’m running EM with BP right now. With 10 EM and 10 BP iterations, I’d like to have a sense for how many iterations it’s successfully completed.

+  +  +  +  +  +  +  +  +  +  +  +
Avi Pfeffer
Charles River Analytics Inc.
apfeffer@cra.com<mailto:apfeffer@cra.com>
(617) 491-3474x513

**Comment by mhoward2718** [comment]
You could add something that writes to a PrintStream or OutputStream to Algorithm, or maybe have it as a trait. Then, when creating an algorithm you could specify where the output should go, if anywhere.

```scala
class ReportProgress(val s : PrintStream){
  def report = {
    s.println("...")
  }
}

object ReportProgress {  
  def apply(s: PrintStream) = new ReportProgress(s)
}

object Test {
  def main(args: Array[String]) {
    val test = ReportProgress(System.out)
  }
}
```

**Comment by apfeffer** [comment]
This comes under the general framework of development environment, so this is now replaced by APPRIL issue #61.
