### ISSUE TITLE
Star not handled correctly in sparse factors

### ISSUE THREAD

**Issue by bruttenberg** [p2t2/figaro#509]
In the space factor creation for apply, each result value of the apply is searched for in the result variable values to get the index. However, searching for the value does not check if any of the values in the result variable are star, which causes an error. The following code with flag this error:

import com.cra.figaro.algorithm.sampling.MetropolisHastings
import com.cra.figaro.algorithm.sampling.ProposalScheme
import com.cra.figaro.language.Apply
import com.cra.figaro.language.Chain
import com.cra.figaro.language.Constant
import com.cra.figaro.language.Element
import com.cra.figaro.language.Flip
import com.cra.figaro.language.Inject
import com.cra.figaro.language.Select
import com.cra.figaro.library.atomic.discrete.Uniform
import com.cra.figaro.algorithm.sampling.Importance
import com.cra.figaro.experimental.structured.algorithm.StructuredVE
import com.cra.figaro.algorithm.lazyfactored.LazyVariableElimination

object pcfg {

   val grammar = Map(
      'S -> (() => { Select(0.25 -> List('A, 'B), 0.2 -> List('B, 'C), 0.4 -> List('A, 'C), 0.15 -> List('C, 'A)) }),
      'A -> (() => { Select(0.05 -> List('a), 0.3 -> List('b), 0.65 -> List('S)) }),
      'B -> (() => { Select(0.5 -> List('b), 0.3 -> List('c), 0.2 -> List('d)) }),
      'C -> (() => { Select(0.35 -> List('d), 0.1 -> List('e), 0.55 -> List('S)) })
   )
  
  def isTerminal(s: Symbol) = {
    s == 'a || s == 'b || s == 'c || s == 'd || s == 'e
  }
  
  def pcfg(symbol: Symbol): Element[List[Symbol]] = {
    if (isTerminal(symbol)) Constant(List(symbol)) else
    {
      val dist = grammar.get(symbol).get()
      Chain(dist, (rule: List[Symbol]) => {
        Apply(Inject(rule.map(pcfg): _*), (x: List[List[Symbol]]) => x.flatten)
      })
    }
    
  }
  
  
  def main(args: Array[String]) {
 
    val sentence = pcfg('S)

    val ve = new LazyVariableElimination(sentence)
    ve.run(10)
    println(ve.probabilityBounds(sentence, List('b, 'd)))
  
  }
}

**Comment by mreposa** [comment]
This code runs to completion with Figaro 4.0, giving the following result: (0.092,0.8278749999999999)
