### ISSUE TITLE
How to make a learnable HMM? (Question)

### ISSUE THREAD

**Issue by mioalter** [p2t2/figaro#533]
Hi,

I can construct an HMM, but I'm having trouble making an HMM with learnable parameters. I'll explain my setup and hopefully you can suggest changes and/or a way forward.  

My HMM is the one from wikipedia https://en.wikipedia.org/wiki/Hidden_Markov_model
in which the hidden states are {Rainy, Sunny} and the observed states are {Walk, Shop, Clean}.
I have
* types `H` and `O` to model the hidden and observed states
* an HMM class
```
class HMM(
    val length : Int
    , val apriori : Array[Double]
    , val rainyT : Array[Double]
    , val sunnyT : Array[Double]
    , val rainyE : Array[Double]
    , val sunnyE : Array[Double]
) {
    val hidden : List[Element[H]] = makeHiddenSequence(length, transition(rainyT, sunnyT), apriori)
    val observed : List[Element[O]] = makeObservedSequence(hidden, emission(rainyE, sunnyE))
}
```

in which `apriori` represents the apriori distribution over hidden states, `rainyT` and `sunnyT` are the rows of the transition matrix, `rainyE` and `sunnyE` are the rows of the emission matrix. I have helper functions, like `transition : (Array[Double], Array[Double]) => (Element[H] => Element[H])` which makes the transition matrix from its rows, that I use to construct the vals `hidden` and `observed` for the given data. 

I am not very clear on how to make a parameterized version of this. Starting from the types in my HMM class, it looks like I want to 
* replace `Array[Double]` with `Parameter[Array[Double]]`
* replace `Select`s defined in terms of `Array` values in my helper functions by `ParameterizedSelect`s 
* write classes `class ParameterizedH(...) extends Parameterized[H]` and `class ParameterizedO(...) extends Parameterized[O]` (I'm a little fuzzy on this)
* replace `List[Element[H]]` with `List[ParameterizedH]` and similarly for `O`.

So, my question: is there a way to set this up that is more easily amenable to making a parameterized version and/or do you have any pointers?

Thanks!
-Mio

**Comment by bruttenberg** [comment]
Hi Mio,

Thanks for your interest in Figaro.

Could you provide a little more information on your problem? For instance, it’s not clear what parameters you want to learn? The transition matrix? The emission matrix? Also, what are the training data? Normally in an HMM the emissions are observable, but in some instances the hidden states could be available for training. Also, are you considering one sequence of transitions to be a learning instance? (and you have multiple sequences)

We don’t have any specific HMM learning algorithms, so you’d have to use EM.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by mioalter** [comment]
Hi Brian, 

thanks for your reply. My plan is to use an  HMM with given training matrix, emission matrix, and a priori distribution to generate a set of observable sequences, then use that set as training data--so each observable sequence is one training instance--to see if I can learn the transition matrix, emission matrix, and a priori distribution from the data. I can use my setup to generate training data, but I want to make a parameterized version on which to learn those parameters.

This is what the function that makes the transition matrix looks like
```
def transition(rainyTransition : Array[Double], sunnyTransition : Array[Double])(e : Element[H]) : Element[H] = {
    
    def transitionGivenState(h : H) : Element[H] = {
        h match {
            case Rainy => Select(rainyTransition(0) -> Rainy, rainyTransition(1) -> Sunny)
            case Sunny => Select(sunnyTransition(0) -> Rainy, sunnyTransition(1) -> Sunny)            
        }
    }
    
    e.flatMap(transitionGivenState) 

}
```
so if I replace `Array[_]`s by `Parameter[Array[_]]`s and `Element`/`Select`s by `ParameterizedSelect`s I'm good, the only problem is that
```
Chain(parent : ParameterizedSelect[T], cpd : T => ParameterizedSelect[U]) : Element[U]
```
not of type `ParameterizedSelect[U]` so I need to extend or modify `Chain` so that `p => Chain(p, fcn)` is of type `ParameterizedSelect[T] => ParameterizedSelect[U]`. From the MAP_Learning example, it looks like I could take advantage of the fact that I have only two hidden states and use an `If` but that would not work for more than two hidden states which is what I would like to do next.

If I could adapt my non-parameterized setup to produce parameterized hidden and observable sequences of types `List[ParameterizedSelect[H]]` and `List[ParameterizedSelect[O]]`, respectively, analogous to my hidden and observable sequences of types `List[Element[H]]` and `List[Element[O]]`, I'm pretty sure I could figure out how to use EM to learn the parameters.

Thanks,
Mio

**Comment by bruttenberg** [comment]
Hi Mio,

Sorry to drop the ball on this, I'm not trying to ignore you, but I've gotten busy. Have you made any progress on this yet?

**Comment by mioalter** [comment]
Hi Brian, 

no worries. I haven't yet, but I'll have more time to try again next week. My fundamental confusion is: I don't see an easy way to `Chain` a `ParameterizedSelect` and a function to make new a `ParameterizedSelect` the way I can `Chain` an `Element` and a function to make a new `Element`. Am I missing something obvious? If not, I'll look more at how `Chain` is implemented for `Element[_]` and see if I can do the same for `Parameterized[_]`.

Thanks,
Mio

**Comment by apfeffer** [comment]
HI Mio,

You should be able to say something like the following (I have not checked this code for correctness):

val color = Select(Dirichlet(2, 3), ‘red, ‘green)
val size =
  CPD(color,
     ‘red -> Select(Dirichlet(1, 2, 3), ‘small, ‘medium, ‘large),
     ‘green -> Select(Dirichlet(1, 1), ‘medium, ‘large))

The type of size should be ParameterizedSelect. (CPD is just syntactic sugar for Chain).

Is this what you’re looking for?

Thanks,

Avi
+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by mioalter** [comment]
Hi Avi,

that definitely looks like what I want! I'll give it a shot.

Thanks!
Mio
