### ISSUE TITLE
Typo in MEAP: syntax to make ParameterizedSelect

### ISSUE THREAD

**Issue by mioalter** [p2t2/figaro#534]
On p.392 of the pdf of Practical Probabilistic Programming v14, in the section on the EM algorithm, it says 

"Given a Dirichlet parameter d, you can use Select(d, List(1, 2, 3)) to create a Select parameterized by d in which the possible outcomes are 1, 2, or 3."

however
```
scala> :t Select(Dirichlet(4,3,2), List(1,2,3))
com.cra.figaro.language.ParameterizedSelect[List[Int]]
```

The thing you want is
```
scala> :t Select(Dirichlet(4,3,2), 1,2,3)
com.cra.figaro.language.ParameterizedSelect[Int]
```

**Comment by bruttenberg** [comment]
Hi Mio,

Thanks, we had actually just discovered this error today as well!

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
Thanks Mio! Appreciated.

Avi

On Dec 9, 2015, at 8:17 PM, Mio Alter <notifications@github.com<mailto:notifications@github.com>> wrote:


On p.392 of the pdf of Practical Probabilistic Programming v14, in the section on the EM algorithm, it says

"Given a Dirichlet parameter d, you can use Select(d, List(1, 2, 3)) to create a Select parameterized by d in which the possible outcomes are 1, 2, or 3."

however

scala> :t Select(Dirichlet(4,3,2), List(1,2,3))
com.cra.figaro.language.ParameterizedSelect[List[Int]]


The thing you want is

scala> :t Select(Dirichlet(4,3,2), 1,2,3)
com.cra.figaro.language.ParameterizedSelect[Int]


-
