### ISSUE TITLE
MAP inference with SFI

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#557]

**Comment by bruttenberg** [comment]
Initial version of MPE VE has been checked in. It seems that doing BP without the backtracking could be pretty easy as well. That is, at each subproblem, it's easy to get a joint max factor over the interface, and we can ignore all the other factors.

**Comment by bruttenberg** [comment]
Let me add that I'm not sure of the optimality of the solution using BP.

**Comment by apfeffer** [comment]
Brian, BP is always an approximation. Do we have a sense of whether the approximation is worse if you use SFI?

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment]
Yes, I guess I meant that the SFI version would seem to be less optimal or more approximate than normal MPE BP. Meaning, you'd run MPE BP on a subproblem, get an approximate maximal factor for that subproblem, then feed that factor into another BP algorithm, and get who knows what out of that. It just seems to me (intuitively) that the more MPE BP algorithms we run, the less we can say about optimality. 

But maybe I'm overthinking this.

**Comment by apfeffer** [comment]
Is this more of an issue than for sum-product BP? It seems you might have the same problems there.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by apfeffer** [comment]
In other words, in ordinary BP, you loop back and forth on the whole model. SFI limits the looping.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com


From: Avi Pfeffer
Sent: Thursday, March 31, 2016 9:47 AM
To: 'p2t2/figaro' <reply@reply.github.com>; p2t2/figaro <figaro@noreply.github.com>
Subject: RE: [p2t2/figaro] MAP inference with SFI (#557)

Is this more of an issue than for sum-product BP? It seems you might have the same problems there.

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment]
True, no worse than normal SFI BP. Ok, I can add this, should be pretty easy.

**Comment by bruttenberg** [comment]
MPE BP for SFI has been checked in.

**Comment by bruttenberg** [comment]
I'm closing this since BP and VE have been checked in
