### ISSUE TITLE
Regression Example Question

### ISSUE THREAD

**Issue by svepe** [p2t2/figaro#560]
I am currently reading through the Practical Probabilist Programming book and I decided to have a look at the examples in the repository here. I am a bit stuck at the regression example. I understand the code, however I am not sure what its purpose is. Could you give me some information about the problem it is solving? I am particularly confused by 

```
for (_ <- 0 until 100) {
    val n = Normal(mean, 1.0)
    n.addConstraint((m: Double) => m + 5)
}
```
and especially the `m+5`. I will make a PR with the suitable comments once I understand it.

**Comment by bruttenberg** [comment]
Hi Svetlin , can you let us know which test/file you are referring to? I'm not sure which file you're talking about.

**Comment by svepe** [comment]
I refer to this example file:

[Regression](https://github.com/p2t2/figaro/blob/master/FigaroExamples/src/main/scala/com/cra/figaro/example/visualization/Regression.scala)

**Comment by apfeffer** [comment]
Hi Svetlin,

This example was intended to test some experimental visualization features that are under development and wasn't vetted as an example. So don't worry about it. It probably should not have been included in the examples directory. I will make a task to remove the visualization examples.

Avi
