### ISSUE TITLE
Trainable model pattern

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#575]
In general, it can be desirable to learn specific kinds of models using special-purpose methods. However, Figaro is designed to be general-purpose and not contain special-purpose code that only applies to a specific model. The following pattern enables such externally trained models to be used in a Figaro program:

trait TrainableModel[I,O] {
  def model(input: I): Element[O]
  def train(data: List[(I,O)]): ()
}
class GP extends TrainableModel ...

val myGP = new GP
myGP.train(data)
val componentModel = Chain(inputModel, myGP.model)

Note that the type of TrainableModel.train implies that both the input and output data are observed. Therefore, the training of TrainableModel.train can be fully separate from any other elements in the Figaro program.

We should add this pattern to the code base and put in examples.

**Comment by dgarant** [comment]
Trait implemented along with GP example in #578

**Comment by AliOC** [comment]
Drop the trait and keep the example for now while we revisit the representation of learning algs.

**Comment by dgarant** [comment]
PR updated
