### ISSUE TITLE
Apply with currying for better type inference

### ISSUE THREAD

**Issue by csenol** [p2t2/figaro#583]
Hi 

Currently writing apply is a bit verbose
` Apply(die1, die2, (i1: Int, i2: Int) => i1 + i2)` 
If Apply used currying we could write it like this
` Apply(die1, die2)(_ + _)`

Is there a reason you do not adopt this approach ? Or maybe it is already  done with some library functions and I am missing it

**Comment by apfeffer** [comment]
Hi,

That’s a good idea! There’s no reason we don’t currently do it, we just didn’t think of it. Do you think you might be able to implement this as a library function?

Thanks,

Avi

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by csenol** [comment]
I'll give it a try. Thanks
