### ISSUE TITLE
Immutability while setting conditions/constraints/observations

### ISSUE THREAD

**Issue by csenol** [p2t2/figaro#584]
Hi

While setting conditions/constraints/observations, we mutate underlying `Element` (maybe Universe, as well). 

Is there a way of doing this without mutation. Such as returning a new Element with modified state and then adding it to the Universe explicitly ?

**Comment by apfeffer** [comment]
Hi,

You know we’ve thought about this. We’ve thought of defining conditions and constraints as a view on observations, so they are imposed on observations from the outside. However, this would require significant modification to the code base and has not been a high enough priority that we wanted to take it on.

Thanks,

Avi

+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com
