### ISSUE TITLE
Calling toString on a compound If makes its result elements permanent

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#586]
This code demonstrates the behavior:
```
val uni = Universe.createNew()
val a = Flip(0.6)
val b = If(a, Flip(0.7), Flip(0.4))

val list1 = uni.permanentElements
b.toString()
val list2 = uni.permanentElements
println(list1)
println(list2)
```
The output is:
```
List(Flip(0.6), If(Flip(0.6), Flip(0.7), Flip(0.4)))
List(Flip(0.6), If(Flip(0.6), Flip(0.7), Flip(0.4)), Flip(0.7), Flip(0.4))
```
This happens because the result elements of a compound `If` element are stored as lazy vals. Normally they are not evaluated, even by inference algorithms, but `toString()` forces their evaluation, which makes them permanent elements in the universe.

Note that the call do `b.toString()` could be replaced by printing out `list1` before computing `list2`. This is because printing `list1` itself makes a call to `b.toString()`. Indeed, I discovered this bug today when I realized that the act of debugging some SFI code was what caused bugs in said SFI code, since several SFI algorithms call universe.permanentElements.

**Comment by bruttenberg** [comment]
I guess I’m not clear why the Flips shouldn’t always be permanent elements, regardless of when they are called?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by wkretschmer** [comment]
This is not at all obvious, but the `Flip(0.7)` and `Flip(0.4)` are not actually elements; they are functions that produce those respective elements. The compound `If` constructor takes the arguments `(test: Element[Boolean], thn: => Element[T], els: => Element[T])`. This is to say that they are not evaluated explicitly as permanent elements in the universe upon construction. This is because in general, the results of a `Chain` are not permanent unless they are defined earlier in the model. It would not be unacceptable to explicitly force the result elements of an `If` to be made permanent, but if that is the case then the code is still incorrect. The result elements cannot be lazily evaluated.

**Comment by bruttenberg** [comment]
If I recall, the then/else clauses were changed to call by reference to so that certain recursive processes could terminate. That is, only the branch of the If that is taken should be evaluated. I don’t know why it’s lazy though. My guess is so that you can create the element without evaluating the clauses.

So what problems does this cause in SFI?

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by wkretschmer** [comment]
The problem is that even though those elements become permanent, factored algorithms won't use those elements. Instead they call the functions `thn` and `els` to make temporary elements. In this sense they treat the compound `If` no differently than a `Chain`. The result is that you can end up with two additional disconnected components in the model that are never used.

Notably, `StructuredMPEVE` fails on models with disconnected components, which could be considered a bug in its own right. This happens because when the final top-level MPE step takes place, if the model has disconnected components, then factors for each component are not combined into a single factor. The `finishMax` function in `VESolver` then always fails to fill the map of recording factors because the check `factorsAfterElimination.size == 1` always fails. So, the algorithm never actually records the MPE values of elements, and therefore querying the algorithm throws a `NoSuchElementException`. The simplest code that demonstrates this is:
```
val a = Flip(0.3)
val b = Flip(0.6)
StructuredMPEVE.mostLikelyValue(b)
```
On the other hand, StructuredMPEBP and MPEVariableElimination both work fine here.

**Comment by apfeffer** [comment]
It looks like the problem with StructuredMPEVE is not related to the laziness of If, as your example demonstrates. As Brian mentioned, the lazy If is necessary to prevent infinite recursions. Would it be possible to fix StructuredMPEVE and keep the lazy If?


+ + + + + + + + + + + + + +
Avi Pfeffer, PhD
Principal Scientist
Charles River Analytics
617.491.3474 x513
ww.cra.com

**Comment by bruttenberg** [comment]
Yes, I agree with Avi here. Sounds like it’s a bug in MPEVE. The ’ factorsAfterElimination.size == 1’ is sort of a hack to let SFI know when to record factors. If you can change that to adapt to possible extra factors, that would be best

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
We will fix MPEVE so it doesn't choke when given disconnected components. We will leave If as is.
