### ISSUE TITLE
[Question] Default value for Apply 

### ISSUE THREAD

**Issue by ssbanerje** [p2t2/figaro#618]
Hi,
I am new to using Figaro.

I am trying to use apply on a list of random values and then creating a single random variable from the list (by ORing the values together).

Consider the code example:
```
val sram = List.fill(NumElems)(Flip(0.1))

// >>>
val init = Apply(Flip(1.0), Flip(1.0), (x: Boolean, y:Boolean) => false) // There must be a better way!
// <<<

val failed = sram.foldLeft(init){ (a, v) => Apply(a, v, ((x: Boolean, y: Boolean) => x||y)) }
```

Here, I have to define `init` as some random Apply2 function for this code (i.e. `foldLeft`) to work. Is this the right way to do this? Or am I doing something really roundabout.

**Comment by mhoward2718** [comment]
Hello.

Figaro has a library of containers, which is an easy way to get what you want. Try something like this:
```scala
    val size = 10
    val prob = 0.4
    def indexToFlip(index: Int) = Flip(prob)//A Figaro container requires a function from an index to elements. 
    val sram = new FixedSizeArray(size, indexToFlip)//FixedSizeArray is a Figaro container with a fixed number of elements
    val or  = sram.foldLeft(false){ case (b1,b2) => b1 || b2 }
```

**Comment by wkretschmer** [comment]
Another option is to tell the Scala compiler what you're trying to do by explicitly making the `foldLeft` work on `Element[Boolean]`:
```scala
val numElems = 10
val sram = List.fill(numElems)(Flip(0.1))
val or = sram.foldLeft[Element[Boolean]](Constant(false))(_ || _)
```
The last bit, `_ || _` is Figaro syntactic sugar for `(a, v) => Apply(a, v, ((x: Boolean, y: Boolean) => x || y))`. This works by an implicit conversion that allows calling operators on elements over primitive types.
