### ISSUE TITLE
Some of my routes doesn't want to be translated

### ISSUE THREAD

**Issue by perffy** [p2t2/figaro#632]
Hi guys,

i have very strange situation. I have translated my routes as described in the documentation. Everything was fine till one moment in which i observed that some of my routes are no translated.

On my website i have a flag for each translation to change the language. By hover on the flags, it changes only the language, but does not translate the route. The strange thing, is that for some routes it works, but for some not. 

For example i have one controller for displaying sport predictions. Here are the routes: 

Route::get(LaravelLocalization::transRoute('routes.prognoses').'.html', ['as' => 'prognoses.index', 'uses' => 'PrognosesController@index']);

Route::get('{sport}-'.LaravelLocalization::transRoute('routes.prognoses').'/{date}.html', ['as' => 'prognoses.sport_date', 'uses' => 'PrognosesController@index'])->where(['sport' => '[a-z]+', 'date' => '[0-9]{4}-[0-9]{1,}-[0-9]{1,}']);

Route::get(LaravelLocalization::transRoute('routes.prognose').'/{id}/{slug}.html', ['as' => 'prognoses.show', 'uses' => 'PrognosesController@show']); 

Here it fails to translate the routes ?

**Comment by bruttenberg** [comment]
Hi, are you sure you have the correct GitHub project? This doesn't look like Figaro...

**Comment by perffy** [comment]
o sorry. i have posted to the wrong github :D
