### ISSUE TITLE
Visualizing underlying PGM

### ISSUE THREAD

**Issue by ssbanerje** [p2t2/figaro#634]
Is there any way to access a representation of the underlying PGM from a Figaro program.

**Comment by bruttenberg** [comment]
We are actually working on a way to visualize a Figaro program. I don’t think it’s ready yet for external use, but hopefully soon.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
