### ISSUE TITLE
Make parameters and parameterized elements work in SFI

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#638]
Currently, we have no way of knowing whether a parameter should be used as an element or its MAP value. However, the MAP value should only be used when we're learning, and we know when that's happening. We should pass this information to the factor creation so it knows what kind of factors to create.

**Comment by bruttenberg** [comment]
Parameter elements also extend ValuesMaker, which was being used incorrectly in SFI. I removed the ValuesMaker trait from parameters, which needs to be considered for a solution
