### ISSUE TITLE
Generalize reachable in util

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#646]
The `reachable` function in `util` finds the vertices in a directed graph that are reachable from a single start vertex. It does not include the start vertex (unless it is reachable from itself). There are use cases for which one wants multiple start vertices, or one wants to include the start vertices in the result. What would be the most sensible way to add these features?

I haven't yet implemented this myself because we might want to change the specification a bit more. Right now, `reachable` returns a `Traversable`, and is guaranteed to return a `Traversable` of the same type as the graph adjacency list. It uses the `++` method of traversable at each step of the recursion, and as a result there are cases where this method takes O(V^2) time as opposed to O(V+E) (in particular, for path graphs). We could guarantee O(V+E) time if we returned a `Set` and added elements more carefully.

Are there any compelling reasons to keep something closer the current specification?

**Comment by apfeffer** [comment]
Hi William,

I don’t think there are any strong reasons for the current implementation, so it’s fine to improve it as long as the current functionality works at least as well.

Why do you want to change it?

Avi

**Comment by wkretschmer** [comment]
I need something like this to propagate changes to components and problems in SFI. You say it's fine to change this method as long as it works as least as well as what we have now. Is this still true if I make it return a `Set` instead of a `Traversable`?

It's worth noting that `reachable` is currently used just once in the codebase, for computing the context contents of an element.

**Comment by apfeffer** [comment]
Then the question is whether having a Set is as good as a Traversable when you get context contents.

**Comment by wkretschmer** [comment]
In my view, yes. I'll go forward with the change since it seems there wasn't much reason for this specification to begin with.
