### ISSUE TITLE
Continuous Time Models for Filtering Algorithms

### ISSUE THREAD

**Issue by ssbanerje** [p2t2/figaro#649]
Does the Figaro language/solvers allow for the description of continuous time models like CTMCs or CTBNs. I couldn't find any examples on how to do this in Figaro?

**Comment by apfeffer** [comment]
Hi Subho,

We don’t currently have continuous time inference in Figaro. We’ve been talking to Christian Shelton who’s a leading expert in continuous time inference and hopefully we will be able to add this in the future.

Avi

**Comment by bruttenberg** [comment]
Avi, I recall you were able to do something continuous with the Container library, but maybe I’m mistaken.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by apfeffer** [comment]
Yes, it’s true, you can define a continuous time process using the Process abstraction. You can do some reasoning with that. However, we don’t have general continuous time inference.
