### ISSUE TITLE
Remove intermediate normalization in SFI

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#659]
All SFI solvers include a normalization step before returning the eliminated factors. As far as we can tell, this is unnecessary and can be removed. If we decide to leave it, we should document (in the code) a compelling reason for doing so.

**Comment by wkretschmer** [comment]
How do we "remove" normalization from Gibbs sampling?

**Comment by apfeffer** [comment]
We're not removing normalization. Instead, we compute bounds on the partition function. See #688 .
