### ISSUE TITLE
API for LSFI

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#662]
Lazy algorithms don't fit into the current framework of ProbQuery, MPE, and MarginalMAP algorithms because of the possibility of having star values. We need a separate API that handles extended values as part of its specification.

There are still some questions as to what should go in this interface. For example, is there a sensible way to return a distribution that contains star? What does it mean to compute expectation and variance over variables with star values?

**Comment by apfeffer** [comment]
This is resolved. We produce bounds on the query. We still need to integrate the UCI solvers so they produce bounds, but that's a different issue.
