### ISSUE TITLE
Compact representation of values in CPTs

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#674]
One of the major bottlenecks of Figaro factored inference is the memory taken by factors. A simple optimization that could help is to represent variable values with one byte instead of their full Scala representation. Instead of using the Scala value, we could use a single byte representing an index into the values. This works if there are <= 128 values, by far the most common case. Otherwise we can use two bytes.

I'd like to hear thoughts on whether this would be a worthwhile savings.

**Comment by bruttenberg** [comment]
That could work. Another fix that is low effort with high value is to switch BasicFactors to use Arrays instead of a Map. SparseFactors could still use the Map. Doing a memory analysis shows that a lot of memory is taken up by the List indices.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by mhoward2718** [comment]
Using a byte might not save as much memory as it should.

In Scala, types like Double, Int, Byte, etc correspond to boxed Java objects and not primitive types. There is considerable storage cost in object headers and object references and the anticipated memory savings frm switching to Byte might be negligible after the required overhead.

However, it is still possible to use primitive types in Scala with the @specialized annotation. There are some drawbacks of this as well, though.

**Comment by apfeffer** [comment]
For factors stored as arrays, we wouldn’t need to store the values of variables at all; they would be implicit from the index.

**Comment by apfeffer** [comment]
It looks like @specialized won’t work here because we want to use these inside a Map, where the key type is erased, so we have to go through the boxing/unboxing. However, we could still store the entire key compactly as the indices of all the variables. We would save a lot of boxing in multidimensional factors. Can you @specialize a string/char array?

**Comment by mhoward2718** [comment]
I wonder how applicable/useful it would be to use (or make a wrapper around) a Java library for primitive collections, like Trove or Colt, instead of Scala ones.

**Comment by wkretschmer** [comment]
Don't we already index into factors using `Int`s instead of variable values?

I like the idea of using arrays for dense factors. You could still bring over this optimization to sparse factors by turning a vector of variable indices (a `List[Int]`) into the index in the corresponding dense factor (an `Int`). I suppose we just have to make sure we don't run into integer overflow. Do we have any known use cases where the product of the sizes of the variable ranges is greater than 2^31?

**Comment by bruttenberg** [comment]
We index into Factors using a List[Int], which is a huge memory overhead. I’m in the process of using an ArraySeq for dense factors, so we’ll see how this helps.

If we have factors over 2^31, probably not much chance for us to solve anyways.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by wkretschmer** [comment]
Obviously a 2^31 size dense factor is impractical. However, it might be possible to have an extremely sparse factor over the same variables. For example, creating a pair from two variables that each have a range of size 256. The corresponding sparse factor has 256^2=65536 nonzero entries, even though the total number of possible indices over the corresponding variables is 256^4=2^32. Maybe this is still beyond our capabilities, but it's important to check.

**Comment by bruttenberg** [comment]
I have a preliminary version of Array factors working. Early tests show about 30-40% improvement in speed, same for memory. Need to test some more and clean up the code, but it's looking hopeful.

**Comment by apfeffer** [comment]
Trove looks promising, but it’s LGPL. Joe, can you check whether the license is compatible with ours?

**Comment by apfeffer** [comment]
Cool! Thanks for doing this so quickly.

**Comment by bruttenberg** [comment]
Here's a test program for the dense factors:

  val m = 75
  val a = FromRange(0, m)
  val b = FromRange(0, m)
  val c = FromRange(0, m)
  val x = a ++ b
  val y = c ++ x
  val g = Chain(Flip(0.9), (b: Boolean) => if (b) x else y)
  a.observe(50)
 
  val alg = () => { 
    val a = StructuredVE(g)
    a.start
    println(a.expectation(g, (i: Int) => i.toDouble))
  }
  val time = com.cra.figaro.util.measureTime(alg, 2, 5)
  println("Average time: " + time)

With Figaro 4.1:
90.69999999999997
90.69999999999997
90.69999999999997
90.69999999999997
90.69999999999997
90.69999999999997
90.69999999999997
Average time: 16.314175896000002

With my DEV 4.2 Figaro:
90.70000000000002
90.70000000000002
90.70000000000003
90.70000000000003
90.70000000000003
90.70000000000002
90.70000000000003
Average time: 7.33152728

Memory is lower, but harder to quantify

**Comment by apfeffer** [comment]
Thank you Brian!

Let’s close this issue now. Brian has taken care of the non-sparse factors. We’ll leave the sparse factors as is for now.

Avi

**Comment by bruttenberg** [comment]
Ok, I will close. FYI, we can also probably save memory by switching the indices for sparse arrays from Lists to Arrays. Lists use about twice as much memory. But not critical at this point.

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>
