### ISSUE TITLE
Element with added constraint

### ISSUE THREAD

**Issue by lambdaofgod** [p2t2/figaro#682]
I don't see how to easily implement adding constraint in an immutable way.
When I have an element e1, how do I define element e2 with added constraint, so that e1 doesn't get any other constraint?

This feature would enable to have filter operation in addition to other 'monadic' operations like map, flatMap etc

**Comment by bruttenberg** [comment]
Hi,

I’m not entirely sure what you’re asking. Constraints are added to elements and, while the constraint function should (but doesn’t have to be) immutable, constraints on the element are mutable. That is, constraints can be added and removed. If you can give an example or more detail on what you’d like to do, I’m sure we can help!

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by lambdaofgod** [comment]
Thanks for response.

What I mean is to have something such that
```scala
val e1: Element[T] = <some element>
val c: Constraint[T] = <some constraint>
val e2: Element[T] = e1.withConstraint(c)
```
will not add anything to e1, but will add it to e2.

**Comment by apfeffer** [comment]
Yes, I can see that it would be great to have that. Unfortunately, due to the design of Figaro, it’s not really feasible. There’s a lot of state in an Element and it would be considerable effort to turn into an immutable data structure.

**Comment by bruttenberg** [comment]
As Avi mentioned, there really is not native support for this in Figaro. But you can fake it using Apply. For example:

val e1: Element[T] = <some element>
def c(T): Double = <some constraint>
val e2: Element[T] = e1.map(t: T => t)
e2.addConstraint(c)

This will create a new element that is essentially a deterministic mapping from e1 to e2, then you place the constraint on e2. Not so elegant, but doable.

**Comment by lambdaofgod** [comment]
That code will mutate e1.

What I was looking for is something with what I can implement filter method for Elements.
For example I don't see how to implement stuff from [Erik Meijer's article](http://queue.acm.org/detail.cfm?id=3055303), but essentialy it seems possible.

**Comment by bruttenberg** [comment]
Maybe I'm misunderstanding the definition of mutation here, but the constraint will be placed solely on e2, which is a different element/random variable than e1. e1 will remained unchanged. Note the map function on an element is short hand for an apply, so e1.map creates a new element.

Can you be more specific in the article about what you'd like to implement?

**Comment by lambdaofgod** [comment]
This [notebook](https://github.com/lambdaofgod/probabilistic-programming/blob/master/notebooks/Making%20money%20using%20math.ipynb) contains an example.
