### ISSUE TITLE
Distribution method in StructuredProbQueryAlgorithm needs different signature

### ISSUE THREAD

**Issue by wkretschmer** [p2t2/figaro#713]
A [method ](https://github.com/p2t2/figaro/blob/DEV4.2/Figaro/src/main/scala/com/cra/figaro/algorithm/structured/algorithm/StructuredProbQueryAlgorithm.scala#L70-L79) in StructuredProbQueryAlgorithm was recently added to return problem components for particular elements. The signature of this method conflicts with the regular distribution method in ProbQueryAlgorithm, which makes it impossible to call the regular distribution method on a single element.

**Comment by gtakata** [comment]
This was written as an adjunct to the Development Environment. It has been in place for some time and hasn't presented problems in the past.

I will check this.
