### ISSUE TITLE
The API documentation link seems to be broken

### ISSUE THREAD

**Issue by matanster** [p2t2/figaro#724]
and it is also broken at www.cra.com/Figaro, I think.

**Comment by mreposa** [comment]
Thank you for catching that.... it's been fixed in the master and DEV5.1 branches.

**Comment by matanster** [comment]
Thanks, but why not also fix the github readme to show the correct link for 5.0? or is 5.1 really imminent?

**Comment by mreposa** [comment]
I updated it for completeness, but when we release we always retire the released branch (in this case DEV5.0) and use the master branch for the current release.
