### ISSUE TITLE
how about MDP or POMDP

### ISSUE THREAD

**Issue by gdhucoder** [p2t2/figaro#725]
can Figaro sovle MDP or POMDP problem ?

**Comment by bruttenberg** [comment]
Hi,

Currently, not really. We can represent an MDP or POMDP, but it doesn’t contain any of the typical value or policy iteration algorithms uses to solve them. One could probably write them though as a Figaro algorithm.

Brian

+  +  +  +  +  +  +  +  +  +  +  +  +  +
Brian Ruttenberg, PhD
Senior Scientist
Decision Management Systems Division
Government Services
Charles River Analytics Inc.
617.491.3474 x730
www.cra.com<http://www.cra.com/>

**Comment by gdhucoder** [comment]
Hi, Dear Brian,

Thanks for you kind reply! I'm just beginning to do a little research on MDP, and trying to combine probabilistic programming with dynamic planners. I found Figaro is a very nice PPS. 
Your previous work is very meaningful! And I love Avi Pfeffer's book.

Yours gdHu

**Comment by apfeffer** [comment]
Hi gdHu,

In a previous probabilistic programming language, IBAL, I actually showed that value iteration for MDPs is a generalization of the algorithm IBAL used. Figaro’s structured variable elimination algorithm is similar to IBAL’s algorithm. I think it’s possible, if you encode the problem in the right way, to express an MDP in Figaro, and recover the value iteration algorithm. But this is not something we have done explicitly.

I’m glad you like my book.

Thanks,

Avi
