### ISSUE TITLE
Broken distributive for Linux 64-bit / Scala 2.11

### ISSUE THREAD

**Issue by Alvs10735** [p2t2/figaro#731]
Hi
When i try to download 
figaro-5.0.0.0-linux-x64-installer.run for Linux 64-bit / Scala 2.11
pop up window show very small size: run File (4,5 МБ)
It seems that file is broken

**Comment by mreposa** [comment]
Hello and thank you for your interest in Figaro. We are looking into the matter and should have a response soon.

**Comment by mreposa** [comment]
Hello.... this has been resolved..... please try the download again and let us know if it's working for you.
